FROM node:alpine3.18 

RUN apk add --no-cache git bash

RUN mkdir -p /home/container
RUN adduser --disabled-password --home /home/container container

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]