FROM node:20-alpine

MAINTAINER Fluffy_Kaiju, <contact@dreemcloud.net>

RUN adduser --disabled-password --home /home/container container

USER container

ENV  USER=container HOME=/home/container

RUN apk add --no-cache git

WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]